StakeEnable		= true	# flag --miner ( true : enable staker , false : disable )
[Eth]
NetworkId	= 89  # flag --networkid
SyncMode	= "full" # flag --syncmode
GasPrice	= 1	# flag --gasprice

[Shh]

[Node]
DataDir	  = "node4/"	# flag --datadir
HTTPHost = "localhost"	# flag --rpcaddr
HTTPPort = 8504 	# flag --rpcport
HTTPModules  = ["personal","db","eth","net","web3","txpool","miner"] # flag --rpcapi
[Node.P2P]
ListenAddr = ":30314"  # flag --port
BootstrapNodes = ["enode://343c5f9bbd1dc77a09f8f1812df43c3626038495e47e0bc5f1e930ff8769faa5fac9ab2c9abd009b8590f23fdfa0d842962577f70ca1b7aafeb0b9e950176139@127.0.0.1:30311"]
# flag --bootnodes

[Ethstats]
[Dashboard]
[Account]
Unlocks  = ["0xf7512329f1fa57838dd710f8471c8c05108373e9"]  # list account slipt in flag --unlock
Passwords = ["PWD_DEVNET"]    				   # list password in environment variable (split by ',') : ex : export PWD_DEVNET=123456,123456789


[Bootnodes]
Mainnet        =[]
Testnet        =[]







